### ISSUE TITLE
problem in buliding environment

### ISSUE THREAD

**Issue by goldcook** [EmptyJackson/policy-guided-diffusion#1]
Sorry to bother you, I meet some problem in building docker image through docker/build.sh. Could I build environment by conda or pip? I can't build environment just through docker/requirements.txt.

**Comment by EmptyJackson** [comment]
Sorry to hear it - could you share the error message when you run the build script? Note that you have to run `./build.sh` from **within** `docker` so it correctly locates the requirements file, i.e., `cd docker && ./build.sh`.

You can build the environment through conda/pip from `requirements.txt`, but there are a few extra steps to install mujoco, d4rl and gym. The dockerfile should give you a rough idea of how to install those!
